# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/Users/What do you want/Desktop/Udemy/Gestion_utilisateurs/ui\fenetrePrincipale.ui',
# licensing of 'c:/Users/What do you want/Desktop/Udemy/Gestion_utilisateurs/ui\fenetrePrincipale.ui' applies.
#
# Created: Sun Dec 29 23:10:00 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_fenetrePrincipale(object):
    def setupUi(self, fenetrePrincipale):
        fenetrePrincipale.setObjectName("fenetrePrincipale")
        fenetrePrincipale.setWindowModality(QtCore.Qt.WindowModal)
        fenetrePrincipale.setEnabled(True)
        fenetrePrincipale.resize(1051, 411)
        self.la_titre = QtWidgets.QLabel(fenetrePrincipale)
        self.la_titre.setGeometry(QtCore.QRect(430, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(18)
        self.la_titre.setFont(font)
        self.la_titre.setAlignment(QtCore.Qt.AlignCenter)
        self.la_titre.setObjectName("la_titre")
        self.GB_informations = QtWidgets.QGroupBox(fenetrePrincipale)
        self.GB_informations.setGeometry(QtCore.QRect(10, 80, 321, 221))
        self.GB_informations.setObjectName("GB_informations")
        self.layoutWidget = QtWidgets.QWidget(self.GB_informations)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 291, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.la_mat = QtWidgets.QLabel(self.layoutWidget)
        self.la_mat.setObjectName("la_mat")
        self.verticalLayout.addWidget(self.la_mat)
        self.la_nom = QtWidgets.QLabel(self.layoutWidget)
        self.la_nom.setObjectName("la_nom")
        self.verticalLayout.addWidget(self.la_nom)
        self.la_prenom = QtWidgets.QLabel(self.layoutWidget)
        self.la_prenom.setObjectName("la_prenom")
        self.verticalLayout.addWidget(self.la_prenom)
        self.la_age = QtWidgets.QLabel(self.layoutWidget)
        self.la_age.setObjectName("la_age")
        self.verticalLayout.addWidget(self.la_age)
        self.la_ville = QtWidgets.QLabel(self.layoutWidget)
        self.la_ville.setObjectName("la_ville")
        self.verticalLayout.addWidget(self.la_ville)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.le_matricule = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_matricule.setObjectName("le_matricule")
        self.gridLayout.addWidget(self.le_matricule, 0, 0, 1, 1)
        self.le_nom = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_nom.setObjectName("le_nom")
        self.gridLayout.addWidget(self.le_nom, 1, 0, 1, 1)
        self.le_prenom = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_prenom.setObjectName("le_prenom")
        self.gridLayout.addWidget(self.le_prenom, 2, 0, 1, 1)
        self.le_age = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_age.setObjectName("le_age")
        self.gridLayout.addWidget(self.le_age, 3, 0, 1, 1)
        self.le_ville = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_ville.setObjectName("le_ville")
        self.gridLayout.addWidget(self.le_ville, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.GB_liste = QtWidgets.QGroupBox(fenetrePrincipale)
        self.GB_liste.setGeometry(QtCore.QRect(490, 80, 551, 221))
        self.GB_liste.setObjectName("GB_liste")
        self.tableView = QtWidgets.QTableView(self.GB_liste)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 531, 191))
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(False)
        self.groupBox = QtWidgets.QGroupBox(fenetrePrincipale)
        self.groupBox.setGeometry(QtCore.QRect(350, 80, 120, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 101, 112))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_ajouter = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_ajouter.setObjectName("btn_ajouter")
        self.verticalLayout_2.addWidget(self.btn_ajouter)
        self.btn_modifier = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_modifier.setObjectName("btn_modifier")
        self.verticalLayout_2.addWidget(self.btn_modifier)
        self.btn_supprimer = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_supprimer.setObjectName("btn_supprimer")
        self.verticalLayout_2.addWidget(self.btn_supprimer)
        self.btn_nettoyer = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_nettoyer.setObjectName("btn_nettoyer")
        self.verticalLayout_2.addWidget(self.btn_nettoyer)
        self.groupBox_2 = QtWidgets.QGroupBox(fenetrePrincipale)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 310, 371, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(21, 30, 338, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_matricule = QtWidgets.QRadioButton(self.widget)
        self.radio_matricule.setObjectName("radio_matricule")
        self.horizontalLayout_2.addWidget(self.radio_matricule)
        self.radio_nom = QtWidgets.QRadioButton(self.widget)
        self.radio_nom.setObjectName("radio_nom")
        self.horizontalLayout_2.addWidget(self.radio_nom)
        self.le_rechercher = QtWidgets.QLineEdit(self.widget)
        self.le_rechercher.setObjectName("le_rechercher")
        self.horizontalLayout_2.addWidget(self.le_rechercher)
        self.btn_rechercher = QtWidgets.QPushButton(self.widget)
        self.btn_rechercher.setObjectName("btn_rechercher")
        self.horizontalLayout_2.addWidget(self.btn_rechercher)
        self.groupBox_3 = QtWidgets.QGroupBox(fenetrePrincipale)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 320, 321, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 20, 301, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_premier = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_premier.setObjectName("btn_premier")
        self.horizontalLayout_3.addWidget(self.btn_premier)
        self.btn_precedent = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_precedent.setObjectName("btn_precedent")
        self.horizontalLayout_3.addWidget(self.btn_precedent)
        self.btn_suivant = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_suivant.setObjectName("btn_suivant")
        self.horizontalLayout_3.addWidget(self.btn_suivant)
        self.btn_dernier = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_dernier.setObjectName("btn_dernier")
        self.horizontalLayout_3.addWidget(self.btn_dernier)

        self.retranslateUi(fenetrePrincipale)
        QtCore.QMetaObject.connectSlotsByName(fenetrePrincipale)

    def retranslateUi(self, fenetrePrincipale):
        fenetrePrincipale.setWindowTitle(QtWidgets.QApplication.translate("fenetrePrincipale", "UsersManagement", None, -1))
        self.la_titre.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Gestion des Utilsateurs", None, -1))
        self.GB_informations.setTitle(QtWidgets.QApplication.translate("fenetrePrincipale", "Informations", None, -1))
        self.la_mat.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Matricule", None, -1))
        self.la_nom.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Nom", None, -1))
        self.la_prenom.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Prénom", None, -1))
        self.la_age.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Age", None, -1))
        self.la_ville.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Ville", None, -1))
        self.GB_liste.setTitle(QtWidgets.QApplication.translate("fenetrePrincipale", "Liste des utilisateurs", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("fenetrePrincipale", "Actions", None, -1))
        self.btn_ajouter.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Ajouter", None, -1))
        self.btn_modifier.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Modifier", None, -1))
        self.btn_supprimer.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Supprimer", None, -1))
        self.btn_nettoyer.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Nettoyer", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("fenetrePrincipale", "Rechercher", None, -1))
        self.radio_matricule.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Matricule", None, -1))
        self.radio_nom.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Nom", None, -1))
        self.btn_rechercher.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "Rechercher", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("fenetrePrincipale", "Parcourir", None, -1))
        self.btn_premier.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "<<", None, -1))
        self.btn_precedent.setText(QtWidgets.QApplication.translate("fenetrePrincipale", "<", None, -1))
        self.btn_suivant.setText(QtWidgets.QApplication.translate("fenetrePrincipale", ">", None, -1))
        self.btn_dernier.setText(QtWidgets.QApplication.translate("fenetrePrincipale", ">>", None, -1))

